### ISSUE TITLE
compilation

### ISSUE THREAD

**Issue by alexb84** [quekky/AdvancedCameraSettings_r3#1]
Hello,

I'm getting this error while trying to use ant.
BUILD FAILED
C:\AdvancedCameraSettings_r3-master\build.xml:12: Cannot find C:\AdvancedCameraSettings_r3-master\nbproject\build-impl.xml imported from C:\AdvancedCameraSettings_r3-master\build.xml

**Comment by GSheltonIII** [comment]
I was having the same issue. Once I pulled it into NetBeans, I was able to generate the nbproject folder, but still can not compile this. :(

**Comment by quekky** [comment]
For such a simple sourcecode, there's no point writing an ant file. IIRC I compile it under netbeans, you might have to delete the build.xml and import into a new project

Program runs only in Windows


For cli:

javac -cp lib\dsj.jar -sourcepath src src\*.java
copy lib\* src
cd src
java -cp .;dsj.jar AdvancedCameraSettingsMain
